"""initial schema

Revision ID: 7df2fd94ed1a
Revises:
Create Date: 2026-05-02 15:49:13.726046+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7df2fd94ed1a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "geo_list",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ipv4_count", sa.Integer(), nullable=False),
        sa.Column("ipv6_count", sa.Integer(), nullable=False),
        sa.Column("custom_count", sa.Integer(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("geo_list", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_geo_list_country"), ["country"], unique=False)

    op.create_table(
        "server",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("host", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("region", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("awg_containers", sa.JSON(), nullable=False),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dns_rule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("domains", sa.JSON(), nullable=False),
        sa.Column("ipset_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["server.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("dns_rule", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_dns_rule_server_id"), ["server_id"], unique=False)

    op.create_table(
        "metrics_points",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("rx_bytes", sa.Integer(), nullable=False),
        sa.Column("tx_bytes", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["server.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("metrics_points", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_metrics_points_server_id"), ["server_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_metrics_points_timestamp"), ["timestamp"], unique=False)

    op.create_table(
        "routing_rule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ipset_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fwmark", sa.Integer(), nullable=False),
        sa.Column("table_id", sa.Integer(), nullable=False),
        sa.Column("via_interface", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("via_gateway", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["server.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("routing_rule", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_routing_rule_server_id"), ["server_id"], unique=False)

    op.create_table(
        "tls_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["server.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("server_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tls_config")
    with op.batch_alter_table("routing_rule", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_routing_rule_server_id"))

    op.drop_table("routing_rule")
    with op.batch_alter_table("metrics_points", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_metrics_points_timestamp"))
        batch_op.drop_index(batch_op.f("ix_metrics_points_server_id"))

    op.drop_table("metrics_points")
    with op.batch_alter_table("dns_rule", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dns_rule_server_id"))

    op.drop_table("dns_rule")
    op.drop_table("server")
    with op.batch_alter_table("geo_list", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_geo_list_country"))

    op.drop_table("geo_list")
    # ### end Alembic commands ###
