/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Audit
         * @description Последние записи аудита. payload не возвращаем в листинге — он может быть большим.
         */
        get: operations["list_audit_api_v1_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Логин по username/password. Возвращает session-JWT + профиль юзера.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description No-op для stateless JWT — фронт сам чистит localStorage.
         *
         *     Эндпоинт нужен для аудит-лога (зафиксировать факт выхода) и под будущий
         *     blacklist при переходе на refresh-tokens.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Возвращает текущего юзера. Используется фронтом при старте для проверки сессии.
         */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/ws-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue Ws Token
         * @description Выдаёт короткоживущий JWT для подключения к /ws/events.
         *
         *     Требует session-Bearer'а; ws-token наследует identity юзера для будущего
         *     user-scoped audit (когда WS начнёт писать в audit-log).
         */
        post: operations["issue_ws_token_api_v1_auth_ws_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geoip/lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Geoip */
        get: operations["list_geoip_api_v1_geoip_lists_get"];
        put?: never;
        /** Create Geoip List */
        post: operations["create_geoip_list_api_v1_geoip_lists_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geoip/lists/{geo_list_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Geoip List */
        delete: operations["delete_geoip_list_api_v1_geoip_lists__geo_list_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Servers */
        get: operations["list_servers_api_v1_servers_get"];
        put?: never;
        /** Create Server */
        post: operations["create_server_api_v1_servers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/servers/provision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Provision Server
         * @description Создаёт Server-record со статусом provisioning, запускает background-таску.
         *
         *     Клиент получает id и сразу подписывается на /provision/stream чтобы видеть лог.
         */
        post: operations["provision_server_api_v1_servers_provision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/servers/{server_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Server */
        get: operations["get_server_api_v1_servers__server_id__get"];
        put?: never;
        post?: never;
        /** Delete Server */
        delete: operations["delete_server_api_v1_servers__server_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/servers/{server_id}/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Clients */
        get: operations["list_clients_api_v1_servers__server_id__clients_get"];
        put?: never;
        /** Create Client */
        post: operations["create_client_api_v1_servers__server_id__clients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/servers/{server_id}/clients/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Client */
        delete: operations["delete_client_api_v1_servers__server_id__clients__client_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/servers/{server_id}/clients/{client_id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Client Config
         * @description Возвращает расшифрованный .conf — для скачивания файла из UI.
         */
        get: operations["get_client_config_api_v1_servers__server_id__clients__client_id__config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/servers/{server_id}/clients/{client_id}/qr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Client Qr
         * @description Прокси PNG-байтов QR-кода с агента (генерируется через qrencode).
         */
        get: operations["get_client_qr_api_v1_servers__server_id__clients__client_id__qr_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/servers/{server_id}/clients/{client_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Client */
        post: operations["start_client_api_v1_servers__server_id__clients__client_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/servers/{server_id}/clients/{client_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Client */
        post: operations["stop_client_api_v1_servers__server_id__clients__client_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/servers/{server_id}/dns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Dns Rules */
        get: operations["list_dns_rules_api_v1_servers__server_id__dns_get"];
        put?: never;
        /** Create Dns Rule */
        post: operations["create_dns_rule_api_v1_servers__server_id__dns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/servers/{server_id}/dns/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply Dns */
        post: operations["apply_dns_api_v1_servers__server_id__dns_apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/servers/{server_id}/dns/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Dns Rule */
        delete: operations["delete_dns_rule_api_v1_servers__server_id__dns__rule_id__delete"];
        options?: never;
        head?: never;
        /** Update Dns Rule */
        patch: operations["update_dns_rule_api_v1_servers__server_id__dns__rule_id__patch"];
        trace?: never;
    };
    "/api/v1/servers/{server_id}/geoip/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Geoip Sync
         * @description Триггер синхронизации списка на агенте: GeoList + ipset_name → POST /v1/geoip/sync.
         */
        post: operations["trigger_geoip_sync_api_v1_servers__server_id__geoip_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/servers/{server_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metrics */
        get: operations["get_metrics_api_v1_servers__server_id__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/servers/{server_id}/provision/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Provision Stream
         * @description SSE-стрим лога онбординга. Реплеит историю + стримит до finish.
         */
        get: operations["provision_stream_api_v1_servers__server_id__provision_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/servers/{server_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Server
         * @description Опрашивает агент и обновляет version/awg_containers/status/last_seen_at в БД.
         */
        post: operations["refresh_server_api_v1_servers__server_id__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/servers/{server_id}/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rules */
        get: operations["list_rules_api_v1_servers__server_id__rules_get"];
        put?: never;
        /** Create Rule */
        post: operations["create_rule_api_v1_servers__server_id__rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/servers/{server_id}/rules/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply Rules
         * @description Берёт всё содержимое таблицы routing_rule для server_id и шлёт на агент.
         */
        post: operations["apply_rules_api_v1_servers__server_id__rules_apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/servers/{server_id}/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Rule */
        delete: operations["delete_rule_api_v1_servers__server_id__rules__rule_id__delete"];
        options?: never;
        head?: never;
        /** Update Rule */
        patch: operations["update_rule_api_v1_servers__server_id__rules__rule_id__patch"];
        trace?: never;
    };
    "/api/v1/servers/{server_id}/tls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tls */
        get: operations["get_tls_api_v1_servers__server_id__tls_get"];
        put?: never;
        /** Apply Tls */
        post: operations["apply_tls_api_v1_servers__server_id__tls_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/servers/{server_id}/token/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate Server Token
         * @description Запрашивает у агента новый Bearer-токен и сохраняет его в БД.
         *
         *     Старый токен моментально становится невалидным — агент перезаписывает env-файл
         *     и обновляет settings.token в памяти ДО ответа.
         */
        post: operations["rotate_server_token_api_v1_servers__server_id__token_rotate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/servers/{server_id}/tunnels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tunnels
         * @description Проксирует /v1/tunnels агента — отдаёт live-список пиров с rx/tx/handshake.
         */
        get: operations["get_tunnels_api_v1_servers__server_id__tunnels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/servers/{server_id}/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Server
         * @description Запускает self-update агента в background-таске. Прогресс отдаётся через
         *     `GET /servers/{id}/update/stream` (SSE), чтобы UI мог рендерить лог как при
         *     онбординге, а HTTP-запрос не висел десятки секунд в ожидании reconnect.
         */
        post: operations["update_server_api_v1_servers__server_id__update_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/servers/{server_id}/update/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Update Stream
         * @description SSE-стрим лога self-update'а. Реплеит историю + стримит до finish.
         */
        get: operations["update_stream_api_v1_servers__server_id__update_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Endpoint that serves Prometheus metrics.
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AcmeChallenge
         * @enum {string}
         */
        AcmeChallenge: "http01" | "dns01";
        /** ApplyDnsResponse */
        ApplyDnsResponse: {
            /**
             * Applied
             * @description Применено правил
             */
            applied: number;
            /**
             * Errors
             * @description Ошибки применения
             */
            errors?: string[];
        };
        /** ApplyRulesResponse */
        ApplyRulesResponse: {
            /**
             * Applied
             * @description Добавлено или изменено правил
             */
            applied: number;
            /**
             * Errors
             * @description Ошибки применения
             */
            errors?: string[];
            /**
             * Skipped
             * @description Правил без изменений
             */
            skipped: number;
        };
        /** AuditEntryResponse */
        AuditEntryResponse: {
            /** Id */
            id: number;
            /** Ip */
            ip: string | null;
            /** Method */
            method: string;
            /** Path */
            path: string;
            /** Server Id */
            server_id: number | null;
            /** Status Code */
            status_code: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** User */
            user: string | null;
        };
        /** AuditListResponse */
        AuditListResponse: {
            /** Entries */
            entries: components["schemas"]["AuditEntryResponse"][];
        };
        /**
         * AuditRange
         * @enum {string}
         */
        AuditRange: "1h" | "24h" | "7d";
        /** AwgClientListResponse */
        AwgClientListResponse: {
            /** Clients */
            clients: components["schemas"]["AwgClientResponse"][];
        };
        /** AwgClientResponse */
        AwgClientResponse: {
            /** Container Name */
            container_name: string;
            /** Country */
            country: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Interface Address */
            interface_address: string | null;
            /** Name */
            name: string;
            /** Peer Endpoint */
            peer_endpoint: string | null;
            /** Peer Pubkey */
            peer_pubkey: string | null;
            /** Server Id */
            server_id: number;
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CreateClientPayload */
        CreateClientPayload: {
            /**
             * Config Text
             * @description Полный .conf-файл
             */
            config_text: string;
            /**
             * Country
             * @description ISO-2 код страны VPN
             */
            country?: string | null;
            /**
             * Name
             * @description Идентификатор клиента (a-z0-9-)
             */
            name: string;
        };
        /**
         * DnsProvider
         * @enum {string}
         */
        DnsProvider: "cloudflare" | "desec" | "route53";
        /** DnsRuleCreate */
        DnsRuleCreate: {
            /**
             * Domains
             * @description Домены для подмены резолва в ipset
             */
            domains: string[];
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Ipset Name
             * @description Куда писать резолвы
             */
            ipset_name: string;
            /**
             * Name
             * @description Группа доменов, для UI
             */
            name: string;
        };
        /** DnsRuleListResponse */
        DnsRuleListResponse: {
            /** Rules */
            rules: components["schemas"]["DnsRuleResponse"][];
        };
        /** DnsRuleResponse */
        DnsRuleResponse: {
            /** Domains */
            domains: string[];
            /** Enabled */
            enabled: boolean;
            /** Id */
            id: number;
            /** Ipset Name */
            ipset_name: string;
            /** Name */
            name: string;
            /** Server Id */
            server_id: number;
        };
        /** DnsRuleUpdate */
        DnsRuleUpdate: {
            /** Domains */
            domains?: string[] | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Ipset Name */
            ipset_name?: string | null;
            /** Name */
            name?: string | null;
        };
        /** GeoIpSyncResponse */
        GeoIpSyncResponse: {
            /**
             * Cidrs Loaded
             * @description Загружено CIDR-блоков
             */
            cidrs_loaded: number;
            /**
             * Duration Ms
             * @description Время выполнения в миллисекундах
             */
            duration_ms: number;
            /**
             * Ipset Name
             * @description Имя применённого ipset
             */
            ipset_name: string;
        };
        /** GeoIpSyncTrigger */
        GeoIpSyncTrigger: {
            /** Custom Cidrs */
            custom_cidrs?: string[];
            /**
             * Geo List Id
             * @description id GeoList, который синхронизируем
             */
            geo_list_id: number;
            /**
             * Ipset Name
             * @description Куда заливать на агенте
             */
            ipset_name: string;
        };
        /** GeoListCreate */
        GeoListCreate: {
            /**
             * Country
             * @description Код страны ISO 3166-1 alpha-2
             */
            country: string;
            /**
             * Name
             * @description Человекочитаемое имя списка
             */
            name: string;
            /**
             * Source Url
             * @description URL zone-файла
             */
            source_url: string;
        };
        /** GeoListListResponse */
        GeoListListResponse: {
            /** Lists */
            lists: components["schemas"]["GeoListResponse"][];
        };
        /** GeoListResponse */
        GeoListResponse: {
            /** Country */
            country: string;
            /** Custom Count */
            custom_count: number;
            /** Id */
            id: number;
            /** Ipv4 Count */
            ipv4_count: number;
            /** Ipv6 Count */
            ipv6_count: number;
            /** Last Synced At */
            last_synced_at: string | null;
            /** Name */
            name: string;
            /** Source Url */
            source_url: string;
            /** Status */
            status: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Token */
            token: string;
            /** Ttl Seconds */
            ttl_seconds: number;
            user: components["schemas"]["UserResponse"];
        };
        /** MetricsPointResponse */
        MetricsPointResponse: {
            /** Rx Bytes */
            rx_bytes: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Tx Bytes */
            tx_bytes: number;
        };
        /**
         * MetricsRange
         * @enum {string}
         */
        MetricsRange: "1h" | "6h" | "24h";
        /** MetricsRangeResponse */
        MetricsRangeResponse: {
            /** Points */
            points: components["schemas"]["MetricsPointResponse"][];
            range: components["schemas"]["MetricsRange"];
        };
        /** PeerInfo */
        PeerInfo: {
            /**
             * Endpoint
             * @description Адрес пира (ip:port)
             */
            endpoint: string | null;
            /**
             * Last Handshake
             * @description Время последнего handshake
             */
            last_handshake: string | null;
            /**
             * Public Key
             * @description Публичный ключ пира WireGuard
             */
            public_key: string;
            /**
             * Rx Bytes
             * @description Принято байт
             */
            rx_bytes: number;
            /**
             * Tx Bytes
             * @description Передано байт
             */
            tx_bytes: number;
        };
        /** ProvisionRequest */
        ProvisionRequest: {
            /**
             * Agent Port
             * @description Порт агента после установки (default 7743)
             */
            agent_port?: number | null;
            /**
             * Host
             * @description DNS-имя или IP сервера
             */
            host: string;
            /**
             * Name
             * @description Человекочитаемое имя
             */
            name: string;
            /** Region */
            region?: string | null;
            /**
             * Ssh Password
             * @description Пароль (либо ssh_private_key)
             */
            ssh_password?: string | null;
            /**
             * Ssh Port
             * @description SSH-порт
             * @default 22
             */
            ssh_port: number;
            /**
             * Ssh Private Key
             * @description Private key в PEM-формате
             */
            ssh_private_key?: string | null;
            /**
             * Ssh User
             * @description SSH-пользователь
             * @default root
             */
            ssh_user: string;
        };
        /** RotateTokenResponse */
        RotateTokenResponse: {
            /**
             * Rotated
             * @description Удалось ли перезаписать токен
             */
            rotated: boolean;
        };
        /**
         * RoutingScope
         * @enum {string}
         */
        RoutingScope: "host" | "container";
        /** RuleCreate */
        RuleCreate: {
            /**
             * Country
             * @description Код страны ISO 3166-1 alpha-2
             */
            country: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Fwmark
             * @description Метка пакета
             */
            fwmark: number;
            /**
             * Ipset Name
             * @description Имя ipset на агенте
             */
            ipset_name: string;
            /**
             * @description Где применять (host|container)
             * @default host
             */
            scope: components["schemas"]["RoutingScope"];
            /**
             * Scope Target
             * @description Имя docker-контейнера для scope=container
             */
            scope_target?: string | null;
            /**
             * Table Id
             * @description Таблица маршрутизации
             */
            table_id: number;
            /**
             * Via Gateway
             * @description Шлюз внутри туннеля
             */
            via_gateway: string;
            /**
             * Via Interface
             * @description Исходящий интерфейс на агенте
             */
            via_interface: string;
        };
        /** RuleListResponse */
        RuleListResponse: {
            /** Rules */
            rules: components["schemas"]["RuleResponse"][];
        };
        /** RuleResponse */
        RuleResponse: {
            /** Country */
            country: string;
            /** Enabled */
            enabled: boolean;
            /** Fwmark */
            fwmark: number;
            /** Id */
            id: number;
            /** Ipset Name */
            ipset_name: string;
            /** Scope */
            scope: string;
            /** Scope Target */
            scope_target: string | null;
            /** Server Id */
            server_id: number;
            /** Table Id */
            table_id: number;
            /** Via Gateway */
            via_gateway: string;
            /** Via Interface */
            via_interface: string;
        };
        /** RuleUpdate */
        RuleUpdate: {
            /** Enabled */
            enabled?: boolean | null;
            /** Fwmark */
            fwmark?: number | null;
            scope?: components["schemas"]["RoutingScope"] | null;
            /** Scope Target */
            scope_target?: string | null;
            /** Table Id */
            table_id?: number | null;
            /** Via Gateway */
            via_gateway?: string | null;
            /** Via Interface */
            via_interface?: string | null;
        };
        /** ServerCreate */
        ServerCreate: {
            /**
             * Host
             * @description DNS-имя или IP агента
             */
            host: string;
            /**
             * Name
             * @description Человекочитаемое имя сервера
             */
            name: string;
            /**
             * Port
             * @description HTTPS-порт агента
             * @default 7743
             */
            port: number;
            /**
             * Region
             * @description Регион/группа для sidebar
             */
            region?: string | null;
            /**
             * Token
             * @description Bearer-токен агента
             */
            token: string;
        };
        /** ServerListResponse */
        ServerListResponse: {
            /** Servers */
            servers: components["schemas"]["ServerResponse"][];
        };
        /** ServerResponse */
        ServerResponse: {
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
            /** Awg Containers */
            awg_containers: string[];
            /** Host */
            host: string;
            /** Id */
            id: number;
            /** Last Seen At */
            last_seen_at: string | null;
            /** Name */
            name: string;
            /** Port */
            port: number;
            /** Region */
            region: string | null;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** TlsApplyResponse */
        TlsApplyResponse: {
            /**
             * Cert Path
             * @description Путь к применённому сертификату на сервере
             */
            cert_path: string;
            /**
             * Domains
             * @description Домены в сертификате
             */
            domains: string[];
            /**
             * Expires At
             * Format: date-time
             * @description Дата истечения сертификата
             */
            expires_at: string;
        };
        /** TlsConfig */
        TlsConfig: {
            /**
             * Cert Path
             * @description Путь к cert.pem на сервере
             */
            cert_path?: string | null;
            /**
             * Cert Pem
             * @description Содержимое cert.pem (base64)
             */
            cert_pem?: string | null;
            /** @description Тип ACME-challenge */
            challenge?: components["schemas"]["AcmeChallenge"] | null;
            /**
             * Dns Api Key
             * @description API-ключ DNS-провайдера
             */
            dns_api_key?: string | null;
            /** @description DNS-провайдер для DNS-01 */
            dns_provider?: components["schemas"]["DnsProvider"] | null;
            /**
             * Domains
             * @description Домены для сертификата
             */
            domains?: string[];
            /**
             * Email
             * @description Email для Let's Encrypt
             */
            email?: string | null;
            /**
             * Key Path
             * @description Путь к key.pem на сервере
             */
            key_path?: string | null;
            /**
             * Key Pem
             * @description Содержимое key.pem (base64)
             */
            key_pem?: string | null;
            /** @description Режим получения сертификата */
            mode: components["schemas"]["TlsMode"];
            /**
             * Port
             * @description Порт агента
             * @default 7743
             */
            port: number;
        };
        /** TlsConfigResponse */
        TlsConfigResponse: {
            /**
             * Config
             * @description Сериализованный TlsConfig (без секретов)
             */
            config: {
                [key: string]: unknown;
            };
            /** Expires At */
            expires_at: string | null;
            /** Server Id */
            server_id: number;
        };
        /**
         * TlsMode
         * @enum {string}
         */
        TlsMode: "upload" | "path" | "acme";
        /** TunnelInfo */
        TunnelInfo: {
            /**
             * Container Name
             * @description Имя Docker-контейнера
             */
            container_name: string;
            /**
             * Interface
             * @description Сетевой интерфейс
             */
            interface: string;
            /**
             * Peers
             * @description Список пиров
             */
            peers: components["schemas"]["PeerInfo"][];
            /** @description Состояние туннеля */
            status: components["schemas"]["TunnelStatus"];
        };
        /**
         * TunnelStatus
         * @enum {string}
         */
        TunnelStatus: "up" | "down" | "degraded";
        /** TunnelsResponse */
        TunnelsResponse: {
            /**
             * Tunnels
             * @description Все AWG-туннели на сервере
             */
            tunnels: components["schemas"]["TunnelInfo"][];
        };
        /** UpdateServerRequest */
        UpdateServerRequest: {
            /**
             * Version
             * @description Целевая версия агента (например 0.2.0)
             */
            version: string;
            /**
             * Wait For Reconnect
             * @description Дождаться появления новой версии
             * @default true
             */
            wait_for_reconnect: boolean;
            /**
             * Wheel Url
             * @description URL wheel-файла на GitHub Releases
             */
            wheel_url: string;
        };
        /** UpdateStartResponse */
        UpdateStartResponse: {
            /** Server Id */
            server_id: number;
            /**
             * Stream Url
             * @description Относительный URL для подписки на лог апдейта через EventSource
             */
            stream_url: string;
            /** Target Version */
            target_version: string;
        };
        /** UserResponse */
        UserResponse: {
            /** Is Admin */
            is_admin: boolean;
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WsTokenResponse */
        WsTokenResponse: {
            /** Token */
            token: string;
            /** Ttl Seconds */
            ttl_seconds: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_audit_api_v1_audit_get: {
        parameters: {
            query?: {
                range?: components["schemas"]["AuditRange"];
                server_id?: number | null;
                limit?: number;
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_ws_token_api_v1_auth_ws_token_post: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WsTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_geoip_api_v1_geoip_lists_get: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoListListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_geoip_list_api_v1_geoip_lists_post: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeoListCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_geoip_list_api_v1_geoip_lists__geo_list_id__delete: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                geo_list_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_servers_api_v1_servers_get: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_server_api_v1_servers_post: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provision_server_api_v1_servers_provision_post: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProvisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_server_api_v1_servers__server_id__get: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                server_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_server_api_v1_servers__server_id__delete: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                server_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_clients_api_v1_servers__server_id__clients_get: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                server_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AwgClientListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_client_api_v1_servers__server_id__clients_post: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                server_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClientPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AwgClientResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_client_api_v1_servers__server_id__clients__client_id__delete: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                server_id: number;
                client_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_client_config_api_v1_servers__server_id__clients__client_id__config_get: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                server_id: number;
                client_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_client_qr_api_v1_servers__server_id__clients__client_id__qr_get: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                server_id: number;
                client_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_client_api_v1_servers__server_id__clients__client_id__start_post: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                server_id: number;
                client_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AwgClientResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_client_api_v1_servers__server_id__clients__client_id__stop_post: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                server_id: number;
                client_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AwgClientResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_dns_rules_api_v1_servers__server_id__dns_get: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                server_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DnsRuleListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_dns_rule_api_v1_servers__server_id__dns_post: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                server_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DnsRuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DnsRuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_dns_api_v1_servers__server_id__dns_apply_post: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                server_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplyDnsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dns_rule_api_v1_servers__server_id__dns__rule_id__delete: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                server_id: number;
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_dns_rule_api_v1_servers__server_id__dns__rule_id__patch: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                server_id: number;
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DnsRuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DnsRuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_geoip_sync_api_v1_servers__server_id__geoip_sync_post: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                server_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeoIpSyncTrigger"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoIpSyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_api_v1_servers__server_id__metrics_get: {
        parameters: {
            query?: {
                range?: components["schemas"]["MetricsRange"];
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                server_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsRangeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provision_stream_api_v1_servers__server_id__provision_stream_get: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                server_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_server_api_v1_servers__server_id__refresh_post: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                server_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_api_v1_servers__server_id__rules_get: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                server_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_rule_api_v1_servers__server_id__rules_post: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                server_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_rules_api_v1_servers__server_id__rules_apply_post: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                server_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplyRulesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_rule_api_v1_servers__server_id__rules__rule_id__delete: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                server_id: number;
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_rule_api_v1_servers__server_id__rules__rule_id__patch: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                server_id: number;
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tls_api_v1_servers__server_id__tls_get: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                server_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TlsConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_tls_api_v1_servers__server_id__tls_post: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                server_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TlsConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TlsApplyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rotate_server_token_api_v1_servers__server_id__token_rotate_post: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                server_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotateTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tunnels_api_v1_servers__server_id__tunnels_get: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                server_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TunnelsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_server_api_v1_servers__server_id__update_post: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                server_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateServerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_stream_api_v1_servers__server_id__update_stream_get: {
        parameters: {
            query?: {
                access_token?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                server_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
