// AUTO-GENERATED by `server/scripts/dump_ws_events.py`. Не редактировать вручную.
// Источник истины — `backend/server/ws/events.py::EventType`.

export type WsEventType =
  | "server.created"
  | "server.updated"
  | "server.deleted"
  | "server.status_changed"
  | "server.metrics"
  | "server.agent_updated"
  | "rule.applied"
  | "dns.applied"
  | "geoip.synced"
  | "tls.applied"
  | "provision.progress"
  | "awg_client.created"
  | "awg_client.deleted"
  | "awg_client.status_changed"
  | "direction.created"
  | "direction.updated"
  | "direction.deleted"
  | "ipset_group.created"
  | "ipset_group.updated"
  | "ipset_group.deleted";
