"""Генерирует TypeScript-литералы для `WsEventType` из backend-`EventType` enum'а.

Регрессия #B2: до этого фронт `WsEventType` поддерживался руками — при
добавлении нового события в `server/ws/events.py::EventType` легко забыть
правку в `frontend/src/api/types.ts`. Теперь — codegen, всегда в синке.

Запуск:
    cd backend && uv run python -m server.scripts.dump_ws_events \\
        > ../frontend/src/api/wsEventTypes.gen.ts

CI должен включать drift-check: запускать скрипт и сравнивать с коммитнутым
файлом (как уже делает openapi.json).
"""

import sys

from server.ws.events import EventType


def main() -> None:
    values = [member.value for member in EventType]
    union = "\n  | ".join(f'"{value}"' for value in values)
    sys.stdout.write(
        "// AUTO-GENERATED by `server/scripts/dump_ws_events.py`. Не редактировать вручную.\n"
        "// Источник истины — `backend/server/ws/events.py::EventType`.\n"
        "\n"
        f"export type WsEventType =\n  | {union};\n",
    )


if __name__ == "__main__":
    main()
